CREATE TABLE IF NOT EXISTS urls (
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name                          VARCHAR(255),
  created_at                    TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS url_checks (
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  status_code                   INTEGER,
  title                         VARCHAR(255),
  h1                            VARCHAR(255),
  description                   TEXT,
  url_id                        BIGINT NOT NULL,
  created_at                    TIMESTAMP NOT NULL
);

ALTER TABLE urls DROP CONSTRAINT IF EXISTS pk_urls;
ALTER TABLE urls ADD CONSTRAINT pk_url PRIMARY KEY (id);

ALTER TABLE url_checks DROP CONSTRAINT IF EXISTS pk_url_checks;
ALTER TABLE url_checks ADD CONSTRAINT pk_url_checks PRIMARY KEY (id);